title: KBase UI Docs
# markdown: kramdown
remote_theme: kbaseIncubator/kbase-github-pages-theme
search_enabled: false
aux_links: 
    "KBase UI Docs on Github":
        - "//github.com/kbaseIncubator/kbase-ui-docs"
    "About KBase":
        - "//kbase.us/about"
navigation:
  menu:
    # - label: Home 
    #   slug: index
    - label: Ant Design
      slug: antd
      menu:
        - label: Theming
        - label: Tips
    - label: Development
      menu:
        - label: Prerequisites
        - label: Setup
        - label: Coding Standards
        - label: IDE
        - label: Documentation
        - label: Unit Testing
        - label: Integration Testing
        - label: QA
        - label: Team
        - label: Deployment
    - label: Plugins
      menu: 
        - label: Architecture
        - label: Create from Scratch
          menu:
              - label: 1. Setup
              - label: 2. Create Repos
              - label: 3. Dev Tools
              - label: 4. Say Hello
              - label: 5. A Quick Refactor
              - label: 6. Setup as Plugin
              - label: 7. Add Ant Design
              - label: 8. Add to KBase UI 
              - label: 9. Add Testing
              - label: 10. Fin
        - label: Create from Template
    - label: Documentation
      menu:
        - label: Overview
        - label: Using Github Pages
        - label: Using TSDoc
        - label: Using TypeDoc
    - label: Getting Started
      slug: getting-started
      menu:
          - label: Prerequisites
          - label: Quick Start
    - label: Guides
    - label: Tools
      menu: 
        - label: Playbook
# markdown: kramdown
# kramdown:
#     highlighter: rouge
#     syntax_highlighter_opts:
#         css_class: highlight
#         block:
#             line_numbers: true